/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspacesRouteImport } from './routes/workspaces'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspacesIndexRouteImport } from './routes/workspaces/index'
import { Route as WorkspacesNewRouteImport } from './routes/workspaces/new'
import { Route as WorkspacesWorkspaceIdRouteImport } from './routes/workspaces/$workspaceId'
import { Route as WorkspacesWorkspaceIdAskRouteImport } from './routes/workspaces/$workspaceId/ask'
import { Route as WorkspacesWorkspaceIdAddRouteImport } from './routes/workspaces/$workspaceId/add'
import { Route as WorkspacesWorkspaceIdReviewProposalIdRouteImport } from './routes/workspaces/$workspaceId/review/$proposalId'

const WorkspacesRoute = WorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspacesIndexRoute = WorkspacesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspacesRoute,
} as any)
const WorkspacesNewRoute = WorkspacesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => WorkspacesRoute,
} as any)
const WorkspacesWorkspaceIdRoute = WorkspacesWorkspaceIdRouteImport.update({
  id: '/$workspaceId',
  path: '/$workspaceId',
  getParentRoute: () => WorkspacesRoute,
} as any)
const WorkspacesWorkspaceIdAskRoute =
  WorkspacesWorkspaceIdAskRouteImport.update({
    id: '/ask',
    path: '/ask',
    getParentRoute: () => WorkspacesWorkspaceIdRoute,
  } as any)
const WorkspacesWorkspaceIdAddRoute =
  WorkspacesWorkspaceIdAddRouteImport.update({
    id: '/add',
    path: '/add',
    getParentRoute: () => WorkspacesWorkspaceIdRoute,
  } as any)
const WorkspacesWorkspaceIdReviewProposalIdRoute =
  WorkspacesWorkspaceIdReviewProposalIdRouteImport.update({
    id: '/review/$proposalId',
    path: '/review/$proposalId',
    getParentRoute: () => WorkspacesWorkspaceIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/workspaces': typeof WorkspacesRouteWithChildren
  '/workspaces/$workspaceId': typeof WorkspacesWorkspaceIdRouteWithChildren
  '/workspaces/new': typeof WorkspacesNewRoute
  '/workspaces/': typeof WorkspacesIndexRoute
  '/workspaces/$workspaceId/add': typeof WorkspacesWorkspaceIdAddRoute
  '/workspaces/$workspaceId/ask': typeof WorkspacesWorkspaceIdAskRoute
  '/workspaces/$workspaceId/review/$proposalId': typeof WorkspacesWorkspaceIdReviewProposalIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/workspaces/$workspaceId': typeof WorkspacesWorkspaceIdRouteWithChildren
  '/workspaces/new': typeof WorkspacesNewRoute
  '/workspaces': typeof WorkspacesIndexRoute
  '/workspaces/$workspaceId/add': typeof WorkspacesWorkspaceIdAddRoute
  '/workspaces/$workspaceId/ask': typeof WorkspacesWorkspaceIdAskRoute
  '/workspaces/$workspaceId/review/$proposalId': typeof WorkspacesWorkspaceIdReviewProposalIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/workspaces': typeof WorkspacesRouteWithChildren
  '/workspaces/$workspaceId': typeof WorkspacesWorkspaceIdRouteWithChildren
  '/workspaces/new': typeof WorkspacesNewRoute
  '/workspaces/': typeof WorkspacesIndexRoute
  '/workspaces/$workspaceId/add': typeof WorkspacesWorkspaceIdAddRoute
  '/workspaces/$workspaceId/ask': typeof WorkspacesWorkspaceIdAskRoute
  '/workspaces/$workspaceId/review/$proposalId': typeof WorkspacesWorkspaceIdReviewProposalIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/workspaces'
    | '/workspaces/$workspaceId'
    | '/workspaces/new'
    | '/workspaces/'
    | '/workspaces/$workspaceId/add'
    | '/workspaces/$workspaceId/ask'
    | '/workspaces/$workspaceId/review/$proposalId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/workspaces/$workspaceId'
    | '/workspaces/new'
    | '/workspaces'
    | '/workspaces/$workspaceId/add'
    | '/workspaces/$workspaceId/ask'
    | '/workspaces/$workspaceId/review/$proposalId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/workspaces'
    | '/workspaces/$workspaceId'
    | '/workspaces/new'
    | '/workspaces/'
    | '/workspaces/$workspaceId/add'
    | '/workspaces/$workspaceId/ask'
    | '/workspaces/$workspaceId/review/$proposalId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  WorkspacesRoute: typeof WorkspacesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspaces': {
      id: '/workspaces'
      path: '/workspaces'
      fullPath: '/workspaces'
      preLoaderRoute: typeof WorkspacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces/': {
      id: '/workspaces/'
      path: '/'
      fullPath: '/workspaces/'
      preLoaderRoute: typeof WorkspacesIndexRouteImport
      parentRoute: typeof WorkspacesRoute
    }
    '/workspaces/new': {
      id: '/workspaces/new'
      path: '/new'
      fullPath: '/workspaces/new'
      preLoaderRoute: typeof WorkspacesNewRouteImport
      parentRoute: typeof WorkspacesRoute
    }
    '/workspaces/$workspaceId': {
      id: '/workspaces/$workspaceId'
      path: '/$workspaceId'
      fullPath: '/workspaces/$workspaceId'
      preLoaderRoute: typeof WorkspacesWorkspaceIdRouteImport
      parentRoute: typeof WorkspacesRoute
    }
    '/workspaces/$workspaceId/ask': {
      id: '/workspaces/$workspaceId/ask'
      path: '/ask'
      fullPath: '/workspaces/$workspaceId/ask'
      preLoaderRoute: typeof WorkspacesWorkspaceIdAskRouteImport
      parentRoute: typeof WorkspacesWorkspaceIdRoute
    }
    '/workspaces/$workspaceId/add': {
      id: '/workspaces/$workspaceId/add'
      path: '/add'
      fullPath: '/workspaces/$workspaceId/add'
      preLoaderRoute: typeof WorkspacesWorkspaceIdAddRouteImport
      parentRoute: typeof WorkspacesWorkspaceIdRoute
    }
    '/workspaces/$workspaceId/review/$proposalId': {
      id: '/workspaces/$workspaceId/review/$proposalId'
      path: '/review/$proposalId'
      fullPath: '/workspaces/$workspaceId/review/$proposalId'
      preLoaderRoute: typeof WorkspacesWorkspaceIdReviewProposalIdRouteImport
      parentRoute: typeof WorkspacesWorkspaceIdRoute
    }
  }
}

interface WorkspacesWorkspaceIdRouteChildren {
  WorkspacesWorkspaceIdAddRoute: typeof WorkspacesWorkspaceIdAddRoute
  WorkspacesWorkspaceIdAskRoute: typeof WorkspacesWorkspaceIdAskRoute
  WorkspacesWorkspaceIdReviewProposalIdRoute: typeof WorkspacesWorkspaceIdReviewProposalIdRoute
}

const WorkspacesWorkspaceIdRouteChildren: WorkspacesWorkspaceIdRouteChildren = {
  WorkspacesWorkspaceIdAddRoute: WorkspacesWorkspaceIdAddRoute,
  WorkspacesWorkspaceIdAskRoute: WorkspacesWorkspaceIdAskRoute,
  WorkspacesWorkspaceIdReviewProposalIdRoute:
    WorkspacesWorkspaceIdReviewProposalIdRoute,
}

const WorkspacesWorkspaceIdRouteWithChildren =
  WorkspacesWorkspaceIdRoute._addFileChildren(
    WorkspacesWorkspaceIdRouteChildren,
  )

interface WorkspacesRouteChildren {
  WorkspacesWorkspaceIdRoute: typeof WorkspacesWorkspaceIdRouteWithChildren
  WorkspacesNewRoute: typeof WorkspacesNewRoute
  WorkspacesIndexRoute: typeof WorkspacesIndexRoute
}

const WorkspacesRouteChildren: WorkspacesRouteChildren = {
  WorkspacesWorkspaceIdRoute: WorkspacesWorkspaceIdRouteWithChildren,
  WorkspacesNewRoute: WorkspacesNewRoute,
  WorkspacesIndexRoute: WorkspacesIndexRoute,
}

const WorkspacesRouteWithChildren = WorkspacesRoute._addFileChildren(
  WorkspacesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  WorkspacesRoute: WorkspacesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
